/* ===============================================================================
   Author       : Senior SQL Server DBA / Software Architect
   Description  : SQL Server Query Optimizer tarafından tespit edilen en yüksek 
                  maliyetli eksik indeksleri analiz eder ve otomatik CREATE script'i üretir.
   Target Engine: SQL Server 2012 ve üzeri
   =============================================================================== */

SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

/*
  SENIOR NOTE: 
  Query Optimizer'ın önerdiği HER indeksi pat diye oluşturmayın!
  1. Zaten var olan benzer bir non-clustered indeks varsa onu genişletin (INCLUDE kolon ekleyin).
  2. Tablodaki write (INSERT/UPDATE/DELETE) maliyetini göz önünde bulundurun.
  3. "ImpactScore" değeri 10.000'in altında olan önerileri genelde göz ardı edin.
*/

SELECT TOP 20
    DB_NAME(mid.database_id) AS DatabaseName,
    OBJECT_NAME(mid.object_id, mid.database_id) AS TableName,
    
    -- Miktar x Maliyet x Tahmini Kazanç = Etki Skoru
    CAST(migs.avg_total_user_cost * migs.avg_user_impact * (migs.user_seeks + migs.user_scans) AS BIGINT) AS ImpactScore,
    
    migs.user_seeks + migs.user_scans AS TotalReadsSaved,
    CAST(migs.avg_user_impact AS NUMERIC(5,2)) AS EstimatedQueryImprovementPct,
    
    -- Otomatik DDL Script Üretimi
    'CREATE INDEX [IX_' + OBJECT_NAME(mid.object_id, mid.database_id) + '_' +
        REPLACE(REPLACE(REPLACE(ISNULL(mid.equality_columns, ''), ', ', '_'), '[', ''), ']', '') +
        CASE WHEN mid.equality_columns IS NOT NULL AND mid.inequality_columns IS NOT NULL THEN '_' ELSE '' END +
        REPLACE(REPLACE(REPLACE(ISNULL(mid.inequality_columns, ''), ', ', '_'), '[', ''), ']', '') + ']' +
        ' ON ' + mid.statement + ' (' + 
        ISNULL(mid.equality_columns, '') + 
        CASE WHEN mid.equality_columns IS NOT NULL AND mid.inequality_columns IS NOT NULL THEN ', ' ELSE '' END +
        ISNULL(mid.inequality_columns, '') + ')' +
        ISNULL(' INCLUDE (' + mid.included_columns + ')', '') + 
        ' WITH (ONLINE = ON, FILLFACTOR = 90);' AS AutoGeneratedCreateIndexDDL

FROM sys.dm_db_missing_index_groups mig
INNER JOIN sys.dm_db_missing_index_group_stats migs ON migs.group_handle = mig.index_group_handle
INNER JOIN sys.dm_db_missing_index_details mid ON mig.index_handle = mid.index_handle
WHERE mid.database_id > 4 -- System DB'ler hariç
ORDER BY ImpactScore DESC;